---
# If you truly have a separate role `redis_role`, keep this include; otherwise remove it.
- name: Include Redis role
  ansible.builtin.include_role:
    name: redis_role
  tags: [cache]
  when: redis_role is defined

- name: Configure Redis with template
  become: true
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart redis
  no_log: true
  tags: [cache, redis]
