---
- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
  become: true

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
  become: true
