---
# API endpoints deployment

- name: Deploy jobs API endpoints
  ansible.builtin.template:
    src: api/jobs.py.j2
    dest: "{{ orchestrator_app_dir }}/api/jobs.py"
    owner: "{{ orchestrator_service_user }}"
    group: "{{ orchestrator_service_group }}"
    mode: "0644"
  become: yes
  notify: restart orchestrator
  tags: [api]

- name: Test jobs API import
  ansible.builtin.command: >
    {{ orchestrator_venv_dir }}/bin/python -c 
    'import sys; sys.path.insert(0, "{{ orchestrator_app_dir }}"); 
    from api.jobs import router; 
    print("✅ Jobs API imported")'
  register: jobs_api_import_test
  changed_when: false
  become: yes
  become_user: "{{ orchestrator_service_user }}"
  tags: [api, validation]

- name: Display jobs API import result
  ansible.builtin.debug:
    msg: "{{ jobs_api_import_test.stdout }}"
  tags: [api, validation]
