---
# Component 10: CopilotKit Adapter - Handlers

- name: restart orchestrator
  ansible.builtin.systemd:
    name: orchestrator
    state: restarted
    daemon_reload: yes
  become: yes
  listen: "restart orchestrator"
