---
# LangGraph Workflow Handlers
# Component 9: LangGraph Workflows

- name: restart orchestrator
  ansible.builtin.systemd:
    name: orchestrator
    state: restarted
    daemon_reload: yes
  become: yes

- name: validate orchestrator
  ansible.builtin.uri:
    url: "http://localhost:{{ orchestrator_port | default(8000) }}/health"
    method: GET
    status_code: 200
  retries: 5
  delay: 2
  register: health_check
  until: health_check.status == 200
