---
# LangGraph Workflow Handlers
# Component 9: LangGraph Workflows

- name: Restart orchestrator
  ansible.builtin.systemd:
    name: orchestrator
    state: restarted
    daemon_reload: true
  become: true

- name: Validate orchestrator
  ansible.builtin.uri:
    url: http://localhost:{{ orchestrator_port | default(8000) }}/health
    method: GET
    status_code: 200
  retries: 5
  delay: 2
  register: health_check
  until: health_check.status == 200
