---
# Systemd service deployment
- name: Deploy systemd service file
  ansible.builtin.template:
    src: shield-orchestrator.service.j2
    dest: /etc/systemd/system/shield-orchestrator.service
    owner: root
    group: root
    mode: "0644"
  become: yes
  notify:
    - reload systemd
    - restart orchestrator
  tags: [service]

- name: Enable orchestrator service
  ansible.builtin.systemd:
    name: shield-orchestrator
    enabled: yes
    daemon_reload: yes
  become: yes
  tags: [service]

- name: Start orchestrator service
  ansible.builtin.systemd:
    name: shield-orchestrator
    state: started
  become: yes
  tags: [service]
