---
# Task: Configure sudo permissions for service management
# Purpose: Allow service user to manage systemd services without password
# Variables used:
#   - service_user: User that runs the application services (default: agent0)
#   - sudo_enabled: Enable/disable sudo configuration (default: true)
#   - app_name: Application name for sudo config (default: hx-citadel)

- name: Ensure sudo package is installed
  ansible.builtin.apt:
    name: sudo
    state: present
  become: true
  when: sudo_enabled | default(true)
  tags:
    - sudo
    - packages

- name: Create sudoers.d configuration for service management
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ app_name | default('hx-citadel') }}-services
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  become: true
  when: sudo_enabled | default(true)
  tags:
    - sudo
    - config

- name: Verify sudo configuration
  ansible.builtin.command: sudo -l -U {{ service_user | default('agent0') }}
  become: true
  changed_when: false
  register: sudo_check
  when: sudo_enabled | default(true)
  tags:
    - sudo
    - validation

- name: Display sudo permissions
  ansible.builtin.debug:
    msg: Sudo permissions configured for {{ service_user | default('agent0') }}
  when:
    - sudo_enabled | default(true)
    - sudo_check is defined
  tags:
    - sudo
    - validation
