---
# ==============================================================================
# HX-Citadel Shield - Base System Setup
# Task Orchestrator - Coordinates all base system setup tasks
# ==============================================================================

# ------------------------------------------------------------------------------
# Core System Setup
# ------------------------------------------------------------------------------
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
  become: yes
  tags:
    - always

- name: Install base packages
  apt:
    name:
      - "python{{ python_version }}"
      - "python{{ python_version }}-venv"
      - git
      - curl
    state: present
  become: yes
  tags:
    - deps

- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ service_user | default('agent0') }}"
    group: "{{ service_group | default('agent0') }}"
    mode: "0755"
  become: yes
  tags:
    - app

- name: Ensure log directory exists
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ service_user | default('agent0') }}"
    group: "{{ service_group | default('agent0') }}"
    mode: "0755"
  become: yes
  tags:
    - app

- name: Create Python virtual environment
  command: "python{{ python_version }} -m venv {{ app_dir }}/venv"
  args:
    creates: "{{ app_dir }}/venv/bin/activate"
  become: yes
  become_user: "{{ service_user | default('agent0') }}"
  tags:
    - python

- name: Install Poetry in the virtual environment
  pip:
    name: poetry
    virtualenv: "{{ app_dir }}/venv"
  become: yes
  become_user: "{{ service_user | default('agent0') }}"
  tags:
    - python

- name: Capture realm configuration
  command: realm list
  register: realm_check
  changed_when: false
  failed_when: realm_check.rc != 0
  tags:
    - security

# ------------------------------------------------------------------------------
# Enhanced System Configuration (Optional)
# ------------------------------------------------------------------------------

- name: Configure logrotate for log management
  include_tasks: 06-logrotate.yml
  when: logrotate_enabled | default(true)
  tags:
    - logrotate
    - optional

- name: Configure sudo permissions for service management
  include_tasks: 07-sudo.yml
  when: sudo_enabled | default(true)
  tags:
    - sudo
    - optional

- name: Set up convenience scripts and shell enhancements
  include_tasks: 08-convenience-scripts.yml
  when: convenience_scripts_enabled | default(true)
  tags:
    - convenience
    - optional

- name: Deploy health check monitoring
  include_tasks: 09-health-check.yml
  when: health_check_enabled | default(true)
  tags:
    - health
    - optional
