---
# ==============================================================================
# HX-Citadel Shield - Base System Setup
# Task Orchestrator - Coordinates all base system setup tasks
# ==============================================================================

# ------------------------------------------------------------------------------
# Core System Setup
# ------------------------------------------------------------------------------
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - always

- name: Install base packages
  ansible.builtin.apt:
    name:
      - python{{ python_version }}
      - python{{ python_version }}-venv
      - git
      - curl
    state: present
  become: true
  tags:
    - deps

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ service_user | default('agent0') }}"
    group: "{{ service_group | default('agent0') }}"
    mode: "0755"
  become: true
  tags:
    - app

- name: Ensure log directory exists
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ service_user | default('agent0') }}"
    group: "{{ service_group | default('agent0') }}"
    mode: "0755"
  become: true
  tags:
    - app

- name: Create Python virtual environment
  ansible.builtin.command: python{{ python_version }} -m venv {{ app_dir }}/venv
  args:
    creates: "{{ app_dir }}/venv/bin/activate"
  become: true
  become_user: "{{ service_user | default('agent0') }}"
  tags:
    - python

- name: Install Poetry in the virtual environment
  ansible.builtin.pip:
    name: poetry
    virtualenv: "{{ app_dir }}/venv"
  become: true
  become_user: "{{ service_user | default('agent0') }}"
  tags:
    - python

- name: Capture realm configuration
  ansible.builtin.command: realm list
  register: realm_check
  changed_when: false
  failed_when: realm_check.rc != 0
  tags:
    - security

# ------------------------------------------------------------------------------
# Enhanced System Configuration (Optional)
# ------------------------------------------------------------------------------

- name: Configure logrotate for log management
  ansible.builtin.include_tasks: "06-logrotate.yml"
  when: logrotate_enabled | default(true)
  tags:
    - logrotate
    - optional

- name: Configure sudo permissions for service management
  ansible.builtin.include_tasks: "07-sudo.yml"
  when: sudo_enabled | default(true)
  tags:
    - sudo
    - optional

- name: Set up convenience scripts and shell enhancements
  ansible.builtin.include_tasks: "08-convenience-scripts.yml"
  when: convenience_scripts_enabled | default(true)
  tags:
    - convenience
    - optional

- name: Deploy health check monitoring
  ansible.builtin.include_tasks: "09-health-check.yml"
  when: health_check_enabled | default(true)
  tags:
    - health
    - optional
