---
- name: Restart services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop: "{{ services_to_restart | default([]) }}"
  when: services_to_restart | length > 0
  become: true
