---
# LightRAG handlers

- name: Restart orchestrator
  ansible.builtin.systemd:
    name: shield-orchestrator.service
    state: restarted
    daemon_reload: true
  become: true
  listen: restart orchestrator
