---
# Component 9: LangGraph Workflows - Workflow Deployment

- name: Create workflows directory
  ansible.builtin.file:
    path: "{{ orchestrator_dir }}/workflows"
    state: directory
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0755"
  tags:
    - langgraph
    - workflows

- name: Deploy workflows __init__.py
  ansible.builtin.template:
    src: workflows/__init__.py.j2
    dest: "{{ orchestrator_dir }}/workflows/__init__.py"
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0644"
  tags:
    - langgraph
    - workflows

- name: Deploy query workflow
  ansible.builtin.template:
    src: workflows/query_workflow.py.j2
    dest: "{{ orchestrator_dir }}/workflows/query_workflow.py"
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0644"
  notify:
    - restart orchestrator
  tags:
    - langgraph
    - workflows

- name: Deploy ingestion workflow
  ansible.builtin.template:
    src: workflows/ingestion_workflow.py.j2
    dest: "{{ orchestrator_dir }}/workflows/ingestion_workflow.py"
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0644"
  notify:
    - restart orchestrator
  tags:
    - langgraph
    - workflows

- name: Deploy workflow manager
  ansible.builtin.template:
    src: workflow_manager.py.j2
    dest: "{{ orchestrator_dir }}/services/workflow_manager.py"
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0644"
  notify:
    - restart orchestrator
  tags:
    - langgraph
    - workflows

- name: Set workflows directory permissions
  ansible.builtin.file:
    path: "{{ orchestrator_dir }}/workflows"
    owner: "{{ orchestrator_user }}"
    group: "{{ orchestrator_group }}"
    mode: "0755"
    recurse: true
  tags:
    - langgraph
    - workflows
