---
- name: Clone FastAPI application repository
  ansible.builtin.git:
    repo: https://github.com/hanax-ai/hx-orchestrator.git
    dest: "{{ app_dir }}/orchestrator"
    version: main
  become: true
  become_user: agent0
  tags:
    - orch

- name: Install FastAPI dependencies with Poetry
  ansible.builtin.command: "{{ app_dir }}/venv/bin/poetry install"
  args:
    chdir: "{{ app_dir }}/orchestrator"
  become: true
  become_user: agent0
  changed_when: false
  tags:
    - orch

- name: Render environment file
  ansible.builtin.template:
    src: orchestrator.env.j2
    dest: "{{ app_dir }}/orchestrator/.env"
    mode: "0600"
  become: true
  become_user: agent0
  notify: restart orchestrator
  tags:
    - orch

- name: Install systemd service for orchestrator
  ansible.builtin.template:
    src: orchestrator.service.j2
    dest: /etc/systemd/system/orchestrator.service
    mode: "0644"
  become: true
  notify: restart orchestrator
  tags:
    - orch

- name: Ensure orchestrator service is running
  ansible.builtin.systemd:
    name: orchestrator
    state: started
    enabled: true
  become: true
  tags:
    - orch
