---
- name: Clone FastAPI application repository
  git:
    repo: https://github.com/hanax-ai/hx-orchestrator.git
    dest: "{{ app_dir }}/orchestrator"
    version: main
  become: yes
  become_user: agent0
  tags:
    - orch

- name: Install FastAPI dependencies with Poetry
  command: "{{ app_dir }}/venv/bin/poetry install"
  args:
    chdir: "{{ app_dir }}/orchestrator"
  become: yes
  become_user: agent0
  tags:
    - orch

- name: Render environment file
  template:
    src: orchestrator.env.j2
    dest: "{{ app_dir }}/orchestrator/.env"
    mode: "0600"
  become: yes
  become_user: agent0
  notify: restart orchestrator
  tags:
    - orch

- name: Install systemd service for orchestrator
  template:
    src: orchestrator.service.j2
    dest: /etc/systemd/system/orchestrator.service
    mode: "0644"
  become: yes
  notify: restart orchestrator
  tags:
    - orch

- name: Ensure orchestrator service is running
  systemd:
    name: orchestrator
    state: started
    enabled: yes
  become: yes
  tags:
    - orch
