---
# Python environment setup

- name: Create Python virtual environment
  ansible.builtin.command: python{{ python_version }} -m venv {{ fastmcp_venv_dir }}
  args:
    creates: "{{ fastmcp_venv_dir }}/bin/python"
  become: true
  become_user: "{{ fastmcp_service_user }}"

- name: Upgrade pip in virtual environment
  ansible.builtin.pip:
    name: pip
    state: present
    virtualenv: "{{ fastmcp_venv_dir }}"
  become: true
  become_user: "{{ fastmcp_service_user }}"

- name: Install wheel and setuptools
  ansible.builtin.pip:
    name:
      - wheel
      - setuptools
    state: present
    virtualenv: "{{ fastmcp_venv_dir }}"
  become: true
  become_user: "{{ fastmcp_service_user }}"
