---
# FastMCP and core dependencies installation

- name: Install FastMCP framework
  ansible.builtin.pip:
    name:
      - "fastmcp>=0.4.0"
      - "pydantic>=2.0.0"
      - "httpx>=0.27.0"
      - "uvicorn>=0.30.0"
      - "python-dotenv>=1.0.0"
      - "structlog>=24.1.0"
    virtualenv: "{{ fastmcp_venv_dir }}"
  become: yes
  become_user: "{{ fastmcp_service_user }}"
  notify: restart fastmcp-server
