---
# FastMCP and core dependencies installation
# TASK-021: Error handling with block/rescue/always pattern

- name: Install FastMCP framework with error handling
  block:
    - name: Install FastMCP framework
      ansible.builtin.pip:
        name:
          - "fastmcp>=0.4.0"
          - "pydantic>=2.0.0"
          - "httpx>=0.27.0"
          - "uvicorn>=0.30.0"
          - "python-dotenv>=1.0.0"
          - "structlog>=24.1.0"
          - "python-multipart>=0.0.6"
          - "pybreaker>=1.0.0"
        virtualenv: "{{ fastmcp_venv_dir }}"
      become: yes
      become_user: "{{ fastmcp_service_user }}"
      notify: restart fastmcp-server
      register: fastmcp_install

    - name: Verify FastMCP installation
      ansible.builtin.command:
        cmd: "{{ fastmcp_venv_dir }}/bin/pip show fastmcp"
      changed_when: false
      register: fastmcp_verify

  rescue:
    - name: Log FastMCP installation failure
      ansible.builtin.debug:
        msg: |
          ⚠️  FastMCP installation failed
          Error: {{ ansible_failed_result | default('Unknown pip error') }}
          
    - name: Retry FastMCP installation with verbose output
      ansible.builtin.pip:
        name:
          - "fastmcp>=0.4.0"
          - "pydantic>=2.0.0"
          - "httpx>=0.27.0"
          - "uvicorn>=0.30.0"
          - "python-dotenv>=1.0.0"
          - "structlog>=24.1.0"
          - "python-multipart>=0.0.6"
          - "pybreaker>=1.0.0"
        virtualenv: "{{ fastmcp_venv_dir }}"
        state: forcereinstall
      become: yes
      become_user: "{{ fastmcp_service_user }}"
      register: fastmcp_retry

    - name: Fail if retry unsuccessful
      ansible.builtin.fail:
        msg: "FastMCP installation failed after retry. Check pip logs in venv."
      when: fastmcp_retry is failed

  always:
    - name: Display FastMCP installation summary
      ansible.builtin.debug:
        msg: |
          FastMCP Installation: {{ 'SUCCESS' if (fastmcp_install is succeeded or fastmcp_retry is succeeded) else 'FAILED' }}
          Virtual Environment: {{ fastmcp_venv_dir }}
          Packages: fastmcp, pydantic, httpx, uvicorn, structlog, pybreaker
