---
# Variable validation.
- name: Validate required Redis variables
  assert:
    that:
      - redis_daemon is defined
      - redis_conf_path is defined
    fail_msg: "Required Redis variables are not defined. Please ensure redis_daemon and redis_conf_path are set."
    success_msg: "Required Redis variables are properly defined."

# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: "{{ redis_conf_dir_mode }}"

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis

# Setup/install tasks.
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Ensure Redis is running and enabled on boot.
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
