---
# Validation tasks for Pydantic AI Agents
# Component 8: Pydantic AI Agents

- name: Wait for orchestrator to be ready
  ansible.builtin.uri:
    url: "http://localhost:{{ orchestrator_port | default(8000) }}/health"
    method: GET
    status_code: 200
  retries: 10
  delay: 3
  register: health_check
  until: health_check.status == 200
  tags: [validation]

- name: Test query router agent execution
  ansible.builtin.command: >
    {{ orchestrator_venv_dir }}/bin/python -c 
    'import asyncio;
    import sys;
    sys.path.insert(0, "{{ orchestrator_app_dir }}");
    from agents.query_router import route_query;
    result = asyncio.run(route_query("What is the capital of France?"));
    print(f"Query routed to {result.path} path with {result.mode} mode");
    assert result.path in ["fast", "deep"], "Invalid path";
    assert result.mode in ["vector", "hybrid", "kg"], "Invalid mode";
    print("Query router test PASSED")'
  register: query_router_test
  changed_when: false
  failed_when: query_router_test.rc != 0
  timeout: 60
  tags: [validation, agents]

- name: Display query router test result
  ansible.builtin.debug:
    msg: "{{ query_router_test.stdout_lines }}"
  tags: [validation]

- name: Test agent manager initialization
  ansible.builtin.command: >
    {{ orchestrator_venv_dir }}/bin/python -c 
    'import asyncio;
    import sys;
    sys.path.insert(0, "{{ orchestrator_app_dir }}");
    from services.agent_manager import agent_manager;
    async def test():
        await agent_manager.initialize();
        health = await agent_manager.healthcheck();
        print(f"Agent manager health: {health}");
        assert health["initialized"] == True, "Manager not initialized";
        await agent_manager.shutdown();
        print("Agent manager test PASSED");
    asyncio.run(test())'
  register: agent_manager_test
  changed_when: false
  failed_when: agent_manager_test.rc != 0
  timeout: 60
  tags: [validation, services]

- name: Display agent manager test result
  ansible.builtin.debug:
    msg: "{{ agent_manager_test.stdout_lines }}"
  tags: [validation]

- name: Display validation summary
  ansible.builtin.debug:
    msg:
      - "✅ Component 8: Pydantic AI Agents deployed successfully!"
      - "✅ pydantic_ai installed and verified"
      - "✅ All 3 agents deployed: web_crawl, doc_process, query_router"
      - "✅ Agent manager operational"
      - "✅ Query router tested successfully"
      - "✅ LiteLLM integration working"
      - ""
      - "Ready for Component 9: LangGraph Workflows"
  tags: [validation]
