---
driver:
  name: docker
platforms:
  - name: ubuntu-24
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true          # needed for Docker-in-Docker in CI image
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    v: true
  lint: |
    yamllint .
    ansible-lint
verifier:
  name: ansible

