---
- name: Deploy database services
  hosts: db_nodes
  become: yes
  roles:
    - postgresql
    - redis
  post_tasks:
    - name: Verify PostgreSQL connectivity
      community.postgresql.postgresql_ping:
        db: "{{ db_name | default('hx_citadel') }}"
        login_user: "{{ db_owner | default('hx_pg') }}"
        login_password: "{{ db_password | default(omit) }}"
        login_unix_socket: "{{ pg_login_unix_socket | default('/var/run/postgresql') }}"
      become: yes
      become_user: postgres
      changed_when: false
      no_log: true
  tags:
    - db
