---
# Component 3: PostgreSQL Integration Deployment
- name: Deploy PostgreSQL Integration to Orchestrator
  hosts: hx-orchestrator-server
  become: yes
  gather_facts: yes
  
  vars_files:
    - ../group_vars/all/vault.yml
  
  vars:
    # Import variables from Component 1 (orchestrator_base_setup)
    orchestrator_service_user: "orchestrator"
    orchestrator_service_group: "orchestrator"
    orchestrator_app_dir: "/opt/hx-citadel-shield/orchestrator"
    orchestrator_venv_dir: "/opt/hx-citadel-shield/orchestrator-venv"
    orchestrator_data_dir: "/opt/hx-citadel-shield/data"
    orchestrator_log_dir: "/var/log/hx-citadel/orchestrator"
  
  roles:
    - orchestrator_postgresql
  
  post_tasks:
    - name: Display deployment summary
      ansible.builtin.debug:
        msg:
          - "============================================================"
          - "Component 3: PostgreSQL Integration - DEPLOYMENT COMPLETE"
          - "============================================================"
          - "Database Server: {{ postgres_host }}"
          - "Database Name: {{ postgres_database }}"
          - "Database User: {{ postgres_user }}"
          - "Connection Pool Size: {{ postgres_pool_size }}"
          - "Schemas: lightrag, jobs, events"
          - "============================================================"
      tags: [always]
