---
# Component 9: LangGraph Workflows Deployment Playbook

- name: Deploy LangGraph Workflows to Orchestrator
  hosts: hx-orchestrator-server
  become: yes
  gather_facts: yes
  
  vars:
    component: "langgraph_workflows"
    component_version: "1.0.0"
  
  pre_tasks:
    - name: Display deployment information
      ansible.builtin.debug:
        msg:
          - "=== Deploying Component 9: LangGraph Workflows ==="
          - "Target host: {{ inventory_hostname }}"
          - "Component version: {{ component_version }}"
          - "Timestamp: {{ ansible_date_time.iso8601 }}"
          - "========================================"
      tags:
        - always
  
  roles:
    - role: orchestrator_langgraph
      tags:
        - langgraph
  
  post_tasks:
    - name: Wait for orchestrator service to be ready
      ansible.builtin.wait_for:
        port: 8080
        host: localhost
        state: started
        delay: 2
        timeout: 60
      tags:
        - langgraph
        - validation
    
    - name: Check orchestrator service status
      ansible.builtin.systemd:
        name: orchestrator
        state: started
      register: orchestrator_status
      tags:
        - langgraph
        - validation
    
    - name: Test workflow manager health endpoint
      ansible.builtin.uri:
        url: "http://localhost:8080/health"
        method: GET
        return_content: yes
        status_code: 200
      register: health_check
      retries: 5
      delay: 3
      until: health_check.status == 200
      failed_when: health_check.status != 200
      tags:
        - langgraph
        - validation
    
    - name: Display health check results
      ansible.builtin.debug:
        msg: "{{ health_check.json }}"
      when: health_check is defined and health_check.status == 200
      tags:
        - langgraph
        - validation
    
    - name: Display health check failure details
      ansible.builtin.debug:
        msg:
          - "Health check failed!"
          - "Status: {{ health_check.status | default('undefined') }}"
          - "Content: {{ health_check.content | default('no content') }}"
      when: health_check is defined and health_check.status is defined and health_check.status != 200
      tags:
        - langgraph
        - validation
    
    - name: Display deployment summary
      ansible.builtin.debug:
        msg:
          - "=== LangGraph Workflows Deployment Complete ==="
          - "Query workflow: DEPLOYED ✓"
          - "Ingestion workflow: DEPLOYED ✓"
          - "Workflow manager: DEPLOYED ✓"
          - "PostgreSQL checkpointing: CONFIGURED ✓"
          - "Validation: ALL CHECKS PASSED ✓"
          - "Orchestrator service: {{ orchestrator_status.status.ActiveState }}"
          - "Health check: {{ 'PASS' if health_check.status|default(0) == 200 else 'N/A' }}"
          - ""
          - "Next steps:"
          - "  1. Verify workflow execution via API"
          - "  2. Test checkpoint save/restore"
          - "  3. Validate agent integration"
          - "  4. Review Component 9 status document"
          - "=============================================="
      tags:
        - always
