---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present
  become: true
  tags:
    - observability

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
  become: true
  tags:
    - observability

- name: Deploy HealthService component
  ansible.builtin.template:
    src: HealthService.py.j2
    dest: "{{ app_dir }}/orchestrator/health_service.py"
    mode: "0644"
  become: true
  become_user: agent0
  tags:
    - observability

- name: Install httpx in virtual environment
  ansible.builtin.pip:
    name: httpx
    virtualenv: "{{ app_dir }}/venv"
  become: true
  become_user: agent0
  tags:
    - observability

- name: Deploy Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  become: true
  notify: restart prometheus
  tags:
    - observability
